const dataObject = [
    { name: "Sl no", key: "sl_no", value: null, type: "string", show: true },
    {
        name: "Business Code",
        key: "business_code",
        value: null,
        type: "string",
        show: true,
        error: "Required Field",
    },
    {
        name: "Customer Number",
        key: "cust_number",
        value: null,
        type: "string",
        show: true,
        error: "Required Field",
    },
    {
        name: "Clear Date",
        key: "clear_date",
        value: null,
        type: "date",
        show: true,
        error: "Required Field",
    },
    {
        name: "Business Year",
        key: "buisness_year",
        value: null,
        type: "string",
        show: true,
        error: "Required Field",
    },
    {
        name: "Document Id",
        key: "doc_id",
        value: null,
        type: "string",
        show: true,
        error: "Required Field",
    },
    {
        name: "Posting Date",
        key: "posting_date",
        value: null,
        type: "date",
        show: true,
        error: "Required Field",
    },
    {
        name: "Document Create Date",
        key: "document_create_date",
        value: null,
        type: "date",
        show: true,
        error: "Required Field",
    },
    {
        name: "Due In Date",
        key: "due_in_date",
        value: null,
        type: "date",
        show: true,
        error: "Required Field",
    },
    {
        name: "Invoice Currency",
        key: "invoice_currency",
        value: null,
        type: "string",
        show: true,
        error: "Required Field",
    },
    {
        name: "Document Type",
        key: "document_type",
        value: null,
        type: "string",
        show: true,
        error: "Required Field",
    },
    {
        name: "Posting Id",
        key: "posting_id",
        value: null,
        type: "string",
        show: true,
        error: "Integer Value Only",
    },
    {
        name: "Total Open Amount",
        key: "total_open_amount",
        value: null,
        type: "string",
        show: true,
        error: "Integer Value Only",
    },
    {
        name: "Baseline Create Date",
        key: "baseline_create_date",
        value: null,
        type: "date",
        show: true,
        error: "Required Field",
    },
    {
        name: "Customer Payment Terms",
        key: "cust_payment_terms",
        value: null,
        type: "string",
        show: true,
        error: "Required Field",
    },
    {
        name: "Invoice Id",
        key: "invoice_id",
        value: null,
        type: "string",
        show: true,
        error: "Required Field",
    },
    {
        name: "",
        key: "business_name",
        value: null,
        type: "string",
        show: false,
    },
    {
        name: "Customer Name",
        key: "name_customer",
        value: null,
        type: "string",
        show: false,
    },
    {
        name: "",
        key: "document_create_date1",
        value: null,
        type: "date",
        show: false,
    },
    { name: "", key: "isOpen", value: null, type: "string", show: false },
    { name: "", key: "predicted", value: null, type: "string", show: false },
    { name: "Aging Bucket", key: "aging_bucket", value: null, type: "string", show: true },
    {
        name: "",
        key: "area_business",
        value: null,
        type: "string",
        show: false,
    },
];

const getDataObject = () => {
    return JSON.parse(JSON.stringify(dataObject));
};

export default getDataObject;
